"""Initial migration - all models fixed

Revision ID: d9392caddf96
Revises: d8dbb16cdb5e
Create Date: 2025-12-27 16:25:09.453401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9392caddf96'
down_revision: Union[str, Sequence[str], None] = 'd8dbb16cdb5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('roles', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
